/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.frc5024.thriftyfield;

public class App implements Runnable {
    
    private Arena arena;

    public static void main(String[] args) {
        new App().run();
    }

    public App() {
        
        // Create an arena
        arena = Arena.getInstance();
    }

    @Override
    public void run() {
        
        // Start the arena
        arena.run();

    }
}
