.TH "model Directory Reference" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBdatabase\&.py\fP"
.br
.ti -1c
.RI "file \fBmatch\&.py\fP"
.br
.ti -1c
.RI "file \fBteam\&.py\fP"
.br
.in -1c
