.TH "arena" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arena
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAllianceStation\fP"
.br
.ti -1c
.RI "class \fBArena\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBarena_loop_period_ms\fP = 10"
.br
.ti -1c
.RI "int \fBds_packet_period_ms\fP = 250"
.br
.ti -1c
.RI "int \fBmatch_end_score_dwell_sec\fP = 3"
.br
.ti -1c
.RI "int \fBpost_timeout_sec\fP = 4"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int arena\&.arena_loop_period_ms = 10"

.PP
Definition at line 14 of file arena\&.py\&.
.SS "int arena\&.ds_packet_period_ms = 250"

.PP
Definition at line 15 of file arena\&.py\&.
.SS "int arena\&.match_end_score_dwell_sec = 3"

.PP
Definition at line 16 of file arena\&.py\&.
.SS "int arena\&.post_timeout_sec = 4"

.PP
Definition at line 17 of file arena\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
