.TH "arena.AllianceStation" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arena.AllianceStation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBteam\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBdriverstation_connection\fP = None"
.br
.ti -1c
.RI "\fBtcp_conn_thread\fP = None"
.br
.ti -1c
.RI "bool \fBastop\fP = False"
.br
.ti -1c
.RI "bool \fBestop\fP = False"
.br
.ti -1c
.RI "bool \fBbypass\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Wrapper around a driverstation_connection and info about the physical alliance station
.fi
.PP
 
.PP
Definition at line 19 of file arena\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def arena\&.AllianceStation\&.__init__ ( self)"

.PP
Definition at line 27 of file arena\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "bool arena\&.AllianceStation\&.astop = False\fC [static]\fP"

.PP
Definition at line 23 of file arena\&.py\&.
.SS "bool arena\&.AllianceStation\&.bypass = False\fC [static]\fP"

.PP
Definition at line 25 of file arena\&.py\&.
.SS "arena\&.AllianceStation\&.driverstation_connection = None\fC [static]\fP"

.PP
Definition at line 21 of file arena\&.py\&.
.SS "bool arena\&.AllianceStation\&.estop = False\fC [static]\fP"

.PP
Definition at line 24 of file arena\&.py\&.
.SS "arena\&.AllianceStation\&.tcp_conn_thread = None\fC [static]\fP"

.PP
Definition at line 22 of file arena\&.py\&.
.SS "arena\&.AllianceStation\&.team"

.PP
Definition at line 28 of file arena\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
