.TH "field/arena.py" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
field/arena.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarena\&.AllianceStation\fP"
.br
.ti -1c
.RI "class \fBarena\&.Arena\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBarena\fP"
.br
.ti -1c
.RI " \fBfield\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBarena\&.arena_loop_period_ms\fP = 10"
.br
.ti -1c
.RI "int \fBarena\&.ds_packet_period_ms\fP = 250"
.br
.ti -1c
.RI "int \fBarena\&.match_end_score_dwell_sec\fP = 3"
.br
.ti -1c
.RI "int \fBarena\&.post_timeout_sec\fP = 4"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
