.TH "consolelog.py" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consolelog.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconsolelog\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconsolelog\&.warn\fP"
.br
.ti -1c
.RI "def \fBconsolelog\&.error\fP"
.br
.ti -1c
.RI "def \fBconsolelog\&.notice\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
