.TH "consolelog" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consolelog
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwarn\fP"
.br
.ti -1c
.RI "def \fBerror\fP"
.br
.ti -1c
.RI "def \fBnotice\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def consolelog\&.error ( text)"

.PP
Definition at line 5 of file consolelog\&.py\&.
.SS "def consolelog\&.notice ( text)"

.PP
Definition at line 8 of file consolelog\&.py\&.
.SS "def consolelog\&.warn ( text)"

.PP
Definition at line 2 of file consolelog\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
