.TH "matchtiming" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matchtiming
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBauto_duration_sec\fP = 15"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int matchtiming\&.auto_duration_sec = 15"

.PP
Definition at line 1 of file matchtiming\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
