.TH "model/match.py" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/match.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmodel\&.match\&.Match\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmodel\&.match\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBmodel\&.match\&.elim_round_names\fP = {1: 'F', 2: 'SF', 4: 'QF', 8: 'EF'}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
