.TH "matchstate.MatchState" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matchstate.MatchState
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpre_match\fP = 0"
.br
.ti -1c
.RI "int \fBstart_match\fP = 1"
.br
.ti -1c
.RI "int \fBwarmup_period\fP = 2"
.br
.ti -1c
.RI "int \fBauto_period\fP = 3"
.br
.ti -1c
.RI "int \fBpause_period\fP = 4"
.br
.ti -1c
.RI "int \fBteleop_period\fP = 5"
.br
.ti -1c
.RI "int \fBpost_match\fP = 6"
.br
.ti -1c
.RI "int \fBtimeout_active\fP = 7"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file matchstate\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "int matchstate\&.MatchState\&.auto_period = 3\fC [static]\fP"

.PP
Definition at line 5 of file matchstate\&.py\&.
.SS "int matchstate\&.MatchState\&.pause_period = 4\fC [static]\fP"

.PP
Definition at line 6 of file matchstate\&.py\&.
.SS "int matchstate\&.MatchState\&.post_match = 6\fC [static]\fP"

.PP
Definition at line 8 of file matchstate\&.py\&.
.SS "int matchstate\&.MatchState\&.pre_match = 0\fC [static]\fP"

.PP
Definition at line 2 of file matchstate\&.py\&.
.SS "int matchstate\&.MatchState\&.start_match = 1\fC [static]\fP"

.PP
Definition at line 3 of file matchstate\&.py\&.
.SS "int matchstate\&.MatchState\&.teleop_period = 5\fC [static]\fP"

.PP
Definition at line 7 of file matchstate\&.py\&.
.SS "int matchstate\&.MatchState\&.timeout_active = 7\fC [static]\fP"

.PP
Definition at line 9 of file matchstate\&.py\&.
.SS "int matchstate\&.MatchState\&.warmup_period = 2\fC [static]\fP"

.PP
Definition at line 4 of file matchstate\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
