.TH "model.match.Match" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.match.Match
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBSave\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP = 0"
.br
.ti -1c
.RI "string \fBtype\fP = ''"
.br
.ti -1c
.RI "string \fBdisplay_name\fP = ''"
.br
.ti -1c
.RI "int \fBtime\fP = 0"
.br
.ti -1c
.RI "int \fBelim_round\fP = 0"
.br
.ti -1c
.RI "int \fBelim_group\fP = 0"
.br
.ti -1c
.RI "int \fBelim_instance\fP = 0"
.br
.ti -1c
.RI "int \fBred1\fP = 0"
.br
.ti -1c
.RI "bool \fBred1_is_surrogate\fP = False"
.br
.ti -1c
.RI "int \fBred2\fP = 0"
.br
.ti -1c
.RI "bool \fBred2_is_surrogate\fP = False"
.br
.ti -1c
.RI "int \fBred3\fP = 0"
.br
.ti -1c
.RI "bool \fBred3_is_surrogate\fP = False"
.br
.ti -1c
.RI "int \fBblue1\fP = 0"
.br
.ti -1c
.RI "bool \fBblue1_is_surrogate\fP = False"
.br
.ti -1c
.RI "int \fBblue2\fP = 0"
.br
.ti -1c
.RI "bool \fBblue2_is_surrogate\fP = False"
.br
.ti -1c
.RI "int \fBblue3\fP = 0"
.br
.ti -1c
.RI "bool \fBblue3_is_surrogate\fP = False"
.br
.ti -1c
.RI "string \fBstatus\fP = ''"
.br
.ti -1c
.RI "int \fBstarted_at\fP = 0"
.br
.ti -1c
.RI "int \fBscore_committed_ad\fP = 0"
.br
.ti -1c
.RI "string \fBwinner\fP = ''"
.br
.ti -1c
.RI "string \fBgsm\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file match\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def model\&.match\&.Match\&.Save ( self,  database)"

.PP
Definition at line 31 of file match\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "int model\&.match\&.Match\&.blue1 = 0\fC [static]\fP"

.PP
Definition at line 19 of file match\&.py\&.
.SS "bool model\&.match\&.Match\&.blue1_is_surrogate = False\fC [static]\fP"

.PP
Definition at line 20 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.blue2 = 0\fC [static]\fP"

.PP
Definition at line 21 of file match\&.py\&.
.SS "bool model\&.match\&.Match\&.blue2_is_surrogate = False\fC [static]\fP"

.PP
Definition at line 22 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.blue3 = 0\fC [static]\fP"

.PP
Definition at line 23 of file match\&.py\&.
.SS "bool model\&.match\&.Match\&.blue3_is_surrogate = False\fC [static]\fP"

.PP
Definition at line 24 of file match\&.py\&.
.SS "string model\&.match\&.Match\&.display_name = ''\fC [static]\fP"

.PP
Definition at line 8 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.elim_group = 0\fC [static]\fP"

.PP
Definition at line 11 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.elim_instance = 0\fC [static]\fP"

.PP
Definition at line 12 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.elim_round = 0\fC [static]\fP"

.PP
Definition at line 10 of file match\&.py\&.
.SS "string model\&.match\&.Match\&.gsm = ''\fC [static]\fP"

.PP
Definition at line 29 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.id = 0\fC [static]\fP"

.PP
Definition at line 6 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.red1 = 0\fC [static]\fP"

.PP
Definition at line 13 of file match\&.py\&.
.SS "bool model\&.match\&.Match\&.red1_is_surrogate = False\fC [static]\fP"

.PP
Definition at line 14 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.red2 = 0\fC [static]\fP"

.PP
Definition at line 15 of file match\&.py\&.
.SS "bool model\&.match\&.Match\&.red2_is_surrogate = False\fC [static]\fP"

.PP
Definition at line 16 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.red3 = 0\fC [static]\fP"

.PP
Definition at line 17 of file match\&.py\&.
.SS "bool model\&.match\&.Match\&.red3_is_surrogate = False\fC [static]\fP"

.PP
Definition at line 18 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.score_committed_ad = 0\fC [static]\fP"

.PP
Definition at line 27 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.started_at = 0\fC [static]\fP"

.PP
Definition at line 26 of file match\&.py\&.
.SS "string model\&.match\&.Match\&.status = ''\fC [static]\fP"

.PP
Definition at line 25 of file match\&.py\&.
.SS "int model\&.match\&.Match\&.time = 0\fC [static]\fP"

.PP
Definition at line 9 of file match\&.py\&.
.SS "string model\&.match\&.Match\&.type = ''\fC [static]\fP"

.PP
Definition at line 7 of file match\&.py\&.
.SS "string model\&.match\&.Match\&.winner = ''\fC [static]\fP"

.PP
Definition at line 28 of file match\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
