.TH "model.team.Team" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.team.Team
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP = 0"
.br
.ti -1c
.RI "string \fBname\fP = ''"
.br
.ti -1c
.RI "string \fBnickname\fP = ''"
.br
.ti -1c
.RI "string \fBcity\fP = ''"
.br
.ti -1c
.RI "int \fBrookie_year\fP = 0"
.br
.ti -1c
.RI "string \fBrobot_name\fP = ''"
.br
.ti -1c
.RI "string \fBwpa_key\fP = ''"
.br
.ti -1c
.RI "bool \fByellow_card\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file team\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "string model\&.team\&.Team\&.city = ''\fC [static]\fP"

.PP
Definition at line 6 of file team\&.py\&.
.SS "int model\&.team\&.Team\&.id = 0\fC [static]\fP"

.PP
Definition at line 3 of file team\&.py\&.
.SS "string model\&.team\&.Team\&.name = ''\fC [static]\fP"

.PP
Definition at line 4 of file team\&.py\&.
.SS "string model\&.team\&.Team\&.nickname = ''\fC [static]\fP"

.PP
Definition at line 5 of file team\&.py\&.
.SS "string model\&.team\&.Team\&.robot_name = ''\fC [static]\fP"

.PP
Definition at line 8 of file team\&.py\&.
.SS "int model\&.team\&.Team\&.rookie_year = 0\fC [static]\fP"

.PP
Definition at line 7 of file team\&.py\&.
.SS "string model\&.team\&.Team\&.wpa_key = ''\fC [static]\fP"

.PP
Definition at line 9 of file team\&.py\&.
.SS "bool model\&.team\&.Team\&.yellow_card = False\fC [static]\fP"

.PP
Definition at line 10 of file team\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
