.TH "model.database" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.database
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDatabase\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBbackups_dir\fP = 'db/backups'"
.br
.ti -1c
.RI "string \fBmigrations_dir\fP = 'db/migrations'"
.br
.ti -1c
.RI "string \fBbase_dir\fP = '\&.'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string model\&.database\&.backups_dir = 'db/backups'"

.PP
Definition at line 4 of file database\&.py\&.
.SS "string model\&.database\&.base_dir = '\&.'"

.PP
Definition at line 7 of file database\&.py\&.
.SS "string model\&.database\&.migrations_dir = 'db/migrations'"

.PP
Definition at line 5 of file database\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
