.TH "model.match" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.match
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatch\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBelim_round_names\fP = {1: 'F', 2: 'SF', 4: 'QF', 8: 'EF'}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "dictionary model\&.match\&.elim_round_names = {1: 'F', 2: 'SF', 4: 'QF', 8: 'EF'}"

.PP
Definition at line 3 of file match\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
