.TH "model.database.Database" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model.database.Database
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "def \fBclose\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "dictionary \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file database\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def model\&.database\&.Database\&.__init__ ( self,  path)"

.PP
Definition at line 22 of file database\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def model\&.database\&.Database\&.close ( self)"

.PP
Definition at line 27 of file database\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "dictionary model\&.database\&.Database\&.data\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  {
        "eventSettingsMap" : {},
        "matchMap"         : [],
        "matchResultMap "  : {},
        "rankingMap"       : {},
        "teamMap"          : {},
        "allianceTeamMap"  : {},
        "lowerThirdMap"    : {},
        "sponsorSlideMap"  : {},
        "scheduleBlockMap" : {}
    }
.fi
.PP
Definition at line 10 of file database\&.py\&.
.SS "model\&.database\&.Database\&.data"

.PP
Definition at line 25 of file database\&.py\&.
.SS "model\&.database\&.Database\&.path"

.PP
Definition at line 23 of file database\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
