.TH "notifiers" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
notifiers
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBNotifyAll\fP (server, arena)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def notifiers\&.NotifyAll ( server,  arena)"

.PP
Definition at line 3 of file notifiers\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
