.TH "websocket/notifiers.py" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocket/notifiers.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBnotifiers\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBnotifiers\&.NotifyAll\fP (server, arena)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
