.TH "score.Score" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
score.Score
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpoints\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file score\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "int score\&.Score\&.points = 0\fC [static]\fP"

.PP
Definition at line 3 of file score\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
