.TH "websocket" 3 "Sat Apr 20 2019" "Version 2019" "DeepSpace" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocket
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBRunWrapper\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconfig\fP = json\&.load(open('\&./config\&.json', 'r'))"
.br
.ti -1c
.RI "\fBserver\fP = WebsocketServer(\fBconfig\fP['websocket_port'], host='0\&.0\&.0\&.0')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def websocket\&.RunWrapper ()"

.PP
Definition at line 10 of file websocket\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "websocket\&.config = json\&.load(open('\&./config\&.json', 'r'))"

.PP
Definition at line 6 of file websocket\&.py\&.
.SS "websocket\&.server = WebsocketServer(\fBconfig\fP['websocket_port'], host='0\&.0\&.0\&.0')"

.PP
Definition at line 8 of file websocket\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DeepSpace from the source code\&.
